blank_issues_enabled: false

contact_links:
  - name: Ask a Question
    url: https://github.com/GC-STEM/cs000/discussions
    about: Ask a question or start a discussion if you are not reporting a problem, improvement, or accessibility barrier.

  - name: Student Support
    url: https://github.com/GC-STEM/cs000/wiki/Student-Support
    about: Find course support resources and help options.
